fix: add textarea component
myparcelnl/js-pdk pull request #137
Opened 2023-03-31 08:58 UTC by wthijmen

2023-04-03 14:33 UTC, EdieLemoine requested changes

2023-04-03 14:33 UTC, EdieLemoine commented on apps/admin-components/src/components/DefaultCodeEditor.vue
> +import DefaultTextArea from './DefaultTextArea.vue';
dit mag niet

2023-04-03 14:33 UTC, EdieLemoine commented on apps/admin-components/src/components/DefaultCodeEditor.vue
> +
enter te veel

2023-04-03 14:33 UTC, EdieLemoine commented on apps/admin-preset-bootstrap4/src/__tests__/testComponents.spec.ts
>    PdkTable: Bootstrap4Table,
ik mis een bootstrap 4 code editor, als je toch bezig bent

2023-04-03 14:33 UTC, EdieLemoine commented on apps/backend-demo/data/db/context/pluginSettingsView.json
> +          "$component": "TextArea",
moet CodeEditor zijn

2023-04-04 07:59 UTC, joerivanveen approved these changes

2023-04-04 14:44 UTC, EdieLemoine requested changes

2023-04-04 14:44 UTC, EdieLemoine commented on apps/admin-components/src/components/DefaultCodeEditor.vue
> +  <PdkTextArea v-model.trim="model" :element="props.element" />
Gewoon `element`, `props` bestaat niet in de template.

2023-04-04 14:44 UTC, EdieLemoine commented on apps/admin-preset-bootstrap4/src/components/Bootstrap4CodeEditor.vue
> +  <textarea :id="id" v-model.trim="model" class="form-control"/>
Je hebt geen eslint gerund hierop

2023-04-04 15:04 UTC, merged