fix(admin): fix select inputs replacing value with first option
myparcelnl/js-pdk pull request #184
Opened 2023-06-26 13:46 UTC by Mark-Ernst

2023-06-26 13:47 UTC, EdieLemoine requested changes

2023-06-26 13:47 UTC, EdieLemoine commented on apps/admin-preset-bootstrap4/src/components/Bootstrap4SelectInput.vue
> +import {type ElementInstance, type OptionsProp, useSelectInputContext} from '@myparcel-pdk/admin'; // eslint-disable-next-line vue/no-unused-properties
```suggestion
import {type ElementInstance, type OptionsProp, useSelectInputContext} from '@myparcel-pdk/admin';
```

2023-06-26 13:50 UTC, EdieLemoine approved these changes

2023-06-28 12:48 UTC, joerivanveen approved these changes

2023-06-28 12:48 UTC, EdieLemoine requested changes

2023-06-28 12:48 UTC, EdieLemoine commented on apps/admin-preset-bootstrap4/src/components/Bootstrap4SelectInput.vue
> +import {type ElementInstance, type OptionsProp, useSelectInputContext} from '@myparcel-pdk/admin';
```suggestion
import {type ElementInstance, type OptionsProp, useSelectInputContext} from '@myparcel-pdk/frontend-admin-core';
```

2023-06-28 12:49 UTC, EdieLemoine approved these changes

2023-06-28 12:54 UTC, merged