fix: allow html in forms
myparcelnl/js-pdk pull request #209
Opened 2024-05-23 13:28 UTC by FlorianSDV

2024-05-29 09:31 UTC, EdieLemoine requested changes
dit is geen fix (er was niets kapot) en ik mis nog changes in de andere 2 FormGroup componenten

2024-05-29 10:13 UTC, EdieLemoine requested changes

2024-05-29 10:13 UTC, EdieLemoine commented on apps/admin-demo/src/components/pdk/DemoFormGroup.vue
> +          v-html="error"></li>
dit hoeft niet, het gaat alleen om de description

2024-05-30 07:51 UTC, joerivanveen approved these changes

2024-05-31 12:43 UTC, EdieLemoine approved these changes

2024-05-31 12:45 UTC, merged