feat: add receipt code to admin
myparcelnl/js-pdk pull request #228
Opened 2024-12-13 13:05 UTC by GravendeelJochem

INT-702

2024-12-17 08:13 UTC, joerivanveen requested changes
Moet de `createReceiptCodeField.ts` niet in een test verankerd worden?

2024-12-18 08:40 UTC, FreekVR requested changes

2024-12-18 08:40 UTC, FreekVR commented on apps/admin/src/forms/shipmentOptions/fields/createReceiptCodeField.ts
> +      if (!(CarrierName.DhlForYou === getFormCarrierName(form) && TriState.On === value)) {
Would be good to add a comment explaining why the behaviour is different here for DHL For You

2024-12-18 08:40 UTC, FreekVR commented on apps/admin/src/forms/shipmentOptions/fields/index.ts
> +export * from './createReceiptCodeField';
missing end of file newline

2025-01-08 09:35 UTC, GravendeelJochem commented
> Moet de `createReceiptCodeField.ts` niet in een test verankerd worden?

Nee, hier is een losse story voor om tests te gaan maken in de JS-PDK

2025-01-09 08:36 UTC, joerivanveen approved these changes

2025-01-10 08:43 UTC, FreekVR approved these changes

2025-01-13 13:06 UTC, merged